---
npm_api_base_url: "http://192.168.206.220:15625"
npm_admin_email: "h.karabane@mibtech.ma"
acme_email: "h.karabane@mibtech.ma"

cert_domains:
  - "*.mibtech.ma"
  - "*.visionhis.ma"
  - "*.myakdital.ma"
